### PR TITLE
Automatically expand persistent partition on RPI 4

### PR DESCRIPTION
**Pull request by jimmykarily**
Fixes: https://github.com/kairos-io/kairos/issues/1762
and: https://github.com/kairos-io/kairos/issues/1448

### CODE REVIEW

**Comment by jimmykarily** [comment]
If we like it, we'll need to also bump the package version so that we can release it.

**Comment by mauromorales** [comment]
I guess it will need a bump of a version somewhere

I wonder if we really need this because the partition is properly expanded sometimes ... what is the easiest way to test this before we release package?

**Comment by jimmykarily** [comment]
> I guess it will need a bump of a version somewhere
> 
> I wonder if we really need this because the partition is properly expanded sometimes ... what is the easiest way to test this before we release package?

I just added that to my cloud-config as described here: https://kairos.io/docs/installation/raspberry/#configure-your-node

To test it as a luet package is more complicated. You'd have to create a luet repository manually (a docker image) and push it somewhere, then refer to it in the framework-profile.

**Comment by jimmykarily** [comment]
I bumped the package version

**Pull request merged**
