### PR TITLE
Fix online status with more than one NIC

### PR DESCRIPTION
**Pull request by bencorrado**
For systems with more than one unconfigured NIC, this allows the system to see any one interface online as enough to proceed with online status. Fixes [kairos:#2898](https://github.com/kairos-io/kairos/issues/2898)

### CODE REVIEW

**Review by Itxaka — CHANGES_REQUESTED** [review]
I would drop the `--ipv4` in case we got a netwokr with only ipv6 maybe? if that is not specified, it seems that it will use the configuration from the device to know which version to use so it may be better that way.

Also this will fail to apss CI becuase you need to bump the minor version of the package, so it gets properly build. Just bump the patch version on https://github.com/kairos-io/packages/blob/main/packages/static/kairos-overlay-files/collection.yaml#L4 :)

**Review by Itxaka — APPROVED** [review]

**Comment by Itxaka** [comment]
hey @bencorrado sorry about this, updating the branch made the version go away as we already bumped it in a different Pr. Could you bump the version? Will merge it afterwards

**Comment by Itxaka** [comment]
oh nice, I can push it as well :D

**Comment by bencorrado** [comment]
Thanks for merging and shepherding me through @Itxaka 

Did this count for #hacktoberfest?  I want a t-shirt!

**Comment by mauromorales** [comment]
@bencorrado I just added the tag, if you are subscribed to hacktoberfest, I would hope that it will eventually show up as counting on their app. As for the kairos tshirt you're in, I'm adding you to the list https://github.com/kairos-io/kairos/discussions/2924

**Pull request merged**
